---
- name: install apache
  apt:
    name: apache2
    state: latest

- name: Start apache2
  service:
    name: apache2
    state: started
    enabled: true

- name: Set apache_name
  set_fact:
    apache_name: apache2
...