---
- name: Apache unistall 
  hosts: nodes
  
  tasks:
  - name: Uninstall httpd service
    package: 
      name: httpd
      state: absent

  - name: Remove index.http
    file: 
      path: '/var/www/html/index.html'
      state: absent
 
  - name: Deny port 80/TCP
    firewalld:
      port: 80/TCP
      state: disable
...
