ftp_path:
    default: '/var/ftp/pub'
    upload: '/var/ftp/pub/upload'
    config: '/etc/vsftpd/vsftpd.conf'
    xferlog_file: '/var/log/xferlog'

ftp_conf:
    anonymous_enable: 'NO'
    local_enable: 'YES'
    write_enable: 'YES'
    local_umask: '022'
    anon_upload_enable: 'NO'
    dirmessage_enable: 'YES'
    xferlog_enable: 'YES'
    connect_from_port_20: 'YES'
    xferlog_std_format: 'YES'
    listen: 'NO'
    listen_ipv6: 'YES'
    pam_service_name: 'vsftpd'
    userlist_enable: 'YES'
    anon_root: '/var/ftp/pub'
    no_anon_password: "YES"